"use client";
import {useEffect,useMemo,useState} from "react";
import {DAY,KEY,add,aggregate,createInitial,expiry,format,fresh,iso,makeMeals,recipeMap,recipes,type Batch,type Kind,type Meal,type State,type Usage,type View} from "./data";

const nav:{id:View;label:string;icon:string}[]=[{id:"home",label:"总览",icon:"⌂"},{id:"plan",label:"两周计划",icon:"▦"},{id:"recipes",label:"菜谱库",icon:"◫"},{id:"stock",label:"库存 / 采购",icon:"◎"}];
export default function Home(){
 const[state,setState]=useState<State>(createInitial),[ready,setReady]=useState(false),[view,setView]=useState<View>("home");
 const[picker,setPicker]=useState<{mealId:string;slot:number;kind:Kind}|null>(null),[usageMeal,setUsageMeal]=useState<string|null>(null),[usageDraft,setUsageDraft]=useState<Record<string,number>>({});
 const[toast,setToast]=useState(""),[filter,setFilter]=useState({q:"",source:"全部",kind:"全部",protein:"全部"});
 useEffect(()=>{try{const x=localStorage.getItem(KEY);if(x)setState(JSON.parse(x))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(state))},[state,ready]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2300);return()=>clearTimeout(t)}},[toast]);
 const pending=state.meals.filter(m=>!m.done),needed=aggregate(pending.flatMap(m=>m.recipeIds));
 const totals=useMemo(()=>{const x=new Map<string,number>();state.stock.forEach(b=>x.set(b.ingredientId,(x.get(b.ingredientId)||0)+b.grams));return x},[state.stock]);
 const gap=needed.reduce((s,x)=>s+Math.max(0,x.grams-(totals.get(x.id)||0)),0),risky=[...state.stock].filter(b=>b.grams>0&&fresh(b.expires).days<=2).sort((a,b)=>a.expires.localeCompare(b.expires));
 const visible=recipes.filter(r=>(!filter.q||`${r.name}${r.ingredients.map(x=>x.name)}`.toLowerCase().includes(filter.q.toLowerCase()))&&(filter.source==="全部"||r.source===filter.source)&&(filter.kind==="全部"||r.kind===filter.kind)&&(filter.protein==="全部"||r.protein===filter.protein));
 const set=(fn:(s:State)=>State)=>setState(s=>fn(s));
 const regenerate=()=>{set(s=>({...s,meals:makeMeals(s.start),usage:[]}));setToast("已按新鲜度优先重新排期")};
 const replace=(id:string)=>{if(!picker)return;set(s=>({...s,meals:s.meals.map(m=>m.id===picker.mealId?{...m,recipeIds:m.recipeIds.map((x,i)=>i===picker.slot?id:x)}:m)}));setPicker(null);setToast("菜式与采购清单已更新")};
 const addVeg=(mealId:string)=>set(s=>({...s,meals:s.meals.map(m=>{if(m.id!==mealId)return m;const next=recipes.find(r=>r.kind==="veg"&&!m.recipeIds.includes(r.id))?.id||"super";return{...m,recipeIds:[...m.recipeIds,next]}})}));
 const openUsage=(m:Meal)=>{const old=state.usage.find(u=>u.mealId===m.id);setUsageDraft(Object.fromEntries(aggregate(m.recipeIds).map(x=>[x.id,old?.amounts[x.id]??x.grams])));setUsageMeal(m.id)};
 const restore=(b:Batch[],old?:Usage)=>b.map(x=>({...x,grams:x.grams+(old?.deductions.filter(d=>d.batchId===x.id).reduce((s,d)=>s+d.grams,0)||0)}));
 const saveUsage=()=>{if(!usageMeal)return;set(s=>{const old=s.usage.find(u=>u.mealId===usageMeal),working=restore(s.stock,old),deductions:Usage["deductions"]=[];Object.entries(usageDraft).forEach(([ingredientId,amount])=>{let left=Math.max(0,amount);working.filter(b=>b.ingredientId===ingredientId&&b.grams>0).sort((a,b)=>a.expires.localeCompare(b.expires)).forEach(b=>{const used=Math.min(left,b.grams);if(used){b.grams-=used;left-=used;deductions.push({batchId:b.id,grams:used})}})});return{...s,stock:working,meals:s.meals.map(m=>m.id===usageMeal?{...m,done:true}:m),usage:[...s.usage.filter(u=>u.mealId!==usageMeal),{mealId:usageMeal,amounts:usageDraft,deductions}]}});setUsageMeal(null);setToast("已按最早到期批次扣减库存")};
 const undo=(mealId:string)=>{set(s=>{const old=s.usage.find(u=>u.mealId===mealId);return{...s,stock:restore(s.stock,old),meals:s.meals.map(m=>m.id===mealId?{...m,done:false}:m),usage:s.usage.filter(u=>u.mealId!==mealId)}});setToast("库存已恢复")};
 const updateBatch=(id:string,patch:Partial<Batch>)=>set(s=>({...s,stock:s.stock.map(b=>b.id===id?{...b,...patch}:b)}));
 const weeks=[0,1].map(w=>{const from=new Date(`${state.start}T12:00:00`).getTime()+w*7*DAY;return aggregate(pending.filter(m=>{const t=new Date(`${m.date}T12:00:00`).getTime();return t>=from&&t<from+7*DAY}).flatMap(m=>m.recipeIds))});
 const allocations=(()=>{const left=new Map(totals);return weeks.map(items=>items.map(x=>{const have=Math.min(left.get(x.id)||0,x.grams);left.set(x.id,(left.get(x.id)||0)-have);return{...x,have,gap:x.grams-have}}))})();
 if(!ready)return <main className="loading">正在整理冰箱与菜谱…</main>;
 const title={home:"晚上好，今天吃得刚刚好。",plan:"两周晚餐，一次安排清楚。",recipes:"从两种饮食灵感里自由挑选。",stock:"先吃什么，冰箱心里有数。"}[view];
 return <main className="app"><Aside view={view} setView={setView}/><section className="content"><header className="top"><div><span className="eyebrow">TWO-WEEK TABLE</span><h1>{title}</h1></div><div className="top-actions"><label><span>规划起始日</span><input type="date" value={state.start} onChange={e=>set(s=>({...s,start:e.target.value,meals:makeMeals(e.target.value),usage:[]}))}/></label><button className="icon" onClick={()=>{setState(createInitial());setView("home");setToast("已恢复示例数据")}}>↻</button></div></header>
 {view==="home"&&<div className="stack"><section className="metrics"><Metric primary title="两周安排" value={`${state.meals.length}`} unit="/ 8 顿" note="2 人份 · 每周采购一次"/><Metric icon="肉" title="已安排荤菜" value={`${state.meals.length*2}`} unit="道" note="鸡 · 猪 · 牛 · 鱼 · 虾"/><Metric icon="购" title="仍需采购" value={(gap/1000).toFixed(1)} unit="kg" note="分 2 批购买更保鲜"/><Metric icon="鲜" title="新鲜度提醒" value={`${risky.length}`} unit="项" note="建议优先处理"/></section><section className="panel calendar"><Title over="14-DAY RHYTHM" title="接下来两周" action={<button className="link" onClick={()=>setView("plan")}>查看完整计划 →</button>}/><div className="dates">{Array.from({length:14},(_,i)=>{const date=add(state.start,i),m=state.meals.find(x=>x.date===date);return <div key={date} className={`${m?"cook":""} ${m?.done?"done":""}`}><small>{new Date(`${date}T12:00:00`).toLocaleDateString("zh-CN",{weekday:"short"})}</small><strong>{new Date(`${date}T12:00:00`).getDate()}</strong><span>{m?(m.done?"已完成":i<7?"第一批":"第二批"):"休息"}</span></div>})}</div><p className="legend"><i/>做饭日 <b/>非做饭日 <span>易腐食材已优先排在每批前段</span></p></section><div className="home-lower"><section className="panel"><Title over="NEXT ON THE TABLE" title="下一顿吃什么" action={<button className="link" onClick={regenerate}>重新智能排期 ↻</button>}/>{state.meals.slice(0,3).map(m=><article className="next" key={m.id}><div className="date"><strong>{new Date(`${m.date}T12:00:00`).getDate()}</strong><small>{new Date(`${m.date}T12:00:00`).toLocaleDateString("zh-CN",{month:"short"})}</small></div><div className="mini">{m.recipeIds.map(id=>{const r=recipeMap.get(id)!;return <span key={id}><i style={{background:r.color}}/><b>{r.name}</b><small>{r.kind==="meat"?r.protein:"植物菜"}</small></span>})}</div><button className="round" onClick={()=>setView("plan")}>→</button></article>)}</section><section className="panel"><Title over="USE FIRST" title="优先吃掉" action={<button className="link" onClick={()=>setView("stock")}>管理库存</button>}/><div className="fresh-list">{risky.slice(0,4).map(b=>{const f=fresh(b.expires);return <div className="fresh" key={b.id}><b className={f.cls}>{b.kind==="meat"?"肉":"菜"}</b><span><strong>{b.name}</strong><small>{b.storage} · {b.grams}g</small></span><em className={f.cls}>{f.text}</em></div>})}</div></section></div></div>}
 {view==="plan"&&<div className="stack"><section className="panel plan-head"><div><span className="eyebrow">SMART SCHEDULE</span><h2>{format(state.start)} 起 · 8 顿晚餐</h2><p>每顿固定 2 荤，素菜位可自由增减；换菜后采购缺口立即更新。</p></div><div><button className="button ghost" onClick={()=>set(s=>({...s,meals:[],usage:[]}))}>清空计划</button><button className="button" onClick={regenerate}>智能生成 8 顿</button></div></section><section className="meal-grid">{state.meals.map((m,index)=><article className={`meal ${m.done?"completed":""}`} key={m.id}><header><div><b>0{index+1}</b><span><h3>{format(m.date)}</h3><small>{index<4?"第一批采购":"第二批采购"}</small></span></div><input type="date" min={state.start} max={add(state.start,13)} value={m.date} onChange={e=>set(s=>({...s,meals:s.meals.map(x=>x.id===m.id?{...x,date:e.target.value}:x)}))}/></header><div className="dishes">{m.recipeIds.map((id,slot)=>{const r=recipeMap.get(id)!;return <div className="dish" key={`${m.id}-${slot}`}><b style={{background:r.color}}>{r.kind==="meat"?"荤":"素"}</b><button onClick={()=>setPicker({mealId:m.id,slot,kind:r.kind})}><strong>{r.name}</strong><small>{r.minutes} 分钟 · {r.method} · {r.spice}</small></button>{r.kind==="veg"&&slot>2?<button className="small-btn" onClick={()=>set(s=>({...s,meals:s.meals.map(x=>x.id===m.id?{...x,recipeIds:x.recipeIds.filter((_,i)=>i!==slot)}:x)}))}>×</button>:<button className="small-btn" onClick={()=>setPicker({mealId:m.id,slot,kind:r.kind})}>换</button>}</div>})}<button className="add" onClick={()=>addVeg(m.id)}>＋ 添加一道素菜</button></div><footer><span>{aggregate(m.recipeIds).reduce((s,x)=>s+x.grams,0)}g 生鲜</span>{m.done?<div><button className="link" onClick={()=>openUsage(m)}>调整用量</button><button className="button ghost small" onClick={()=>undo(m.id)}>撤销完成</button></div>:<button className="button small" onClick={()=>openUsage(m)}>✓ 标记完成</button>}</footer></article>)}{!state.meals.length&&<div className="panel blank"><b>空</b><h2>两周计划还是空的</h2><p>让系统安排 8 个做饭日和对应菜式。</p><button className="button" onClick={regenerate}>智能生成 8 顿</button></div>}</section></div>}
 {view==="recipes"&&<div className="stack"><section className="panel filters"><label>⌕<input placeholder="搜索菜名或主要食材" value={filter.q} onChange={e=>setFilter({...filter,q:e.target.value})}/></label><select value={filter.source} onChange={e=>setFilter({...filter,source:e.target.value})}><option>全部</option><option>Bryan Johnson</option><option>泡厨房的顾小胖</option></select><select value={filter.kind} onChange={e=>setFilter({...filter,kind:e.target.value})}><option>全部</option><option value="meat">荤菜</option><option value="veg">植物菜</option></select><select value={filter.protein} onChange={e=>setFilter({...filter,protein:e.target.value})}><option>全部</option><option>鸡肉</option><option>猪肉</option><option>牛肉</option><option>鱼类</option><option>虾类</option></select></section><div className="intro"><div><span className="eyebrow">CURATED FOR TWO</span><h2>{visible.length} 道两人份适配菜谱</h2></div><p>原料克数已为库存核算统一适配，并非视频原始精确配方。</p></div><section className="recipe-grid">{visible.map(r=><article className="recipe" key={r.id}><div className="art" style={{background:r.color}}><span>{r.kind==="meat"?r.protein?.[0]:"植"}</span><i/><b/></div><div className="recipe-body"><div><em>{r.source==="Bryan Johnson"?"BLUEPRINT":"顾小胖灵感"}</em><em>2 人份适配</em></div><h3>{r.name}</h3><p>{r.ingredients.map(x=>`${x.name} ${x.grams}g`).join(" · ")}</p><small>◷ {r.minutes} 分钟　{r.method}　{r.spice}</small><a href={r.link} target="_blank" rel="noreferrer">查看创作来源 ↗</a></div></article>)}</section></div>}
 {view==="stock"&&<div className="stack"><section className="shopping">{[0,1].map(w=><article className="panel" key={w}><Title over={`SHOPPING BATCH 0${w+1}`} title={`第 ${w+1} 周采购`} action={<em>{allocations[w].filter(x=>x.gap>0).length} 项待买</em>}/><div className="shop-head"><span>食材</span><span>计划</span><span>库存</span><span>仍需</span></div>{allocations[w].map(x=><div className="shop-row" key={x.id}><span><i className={x.kind}/>{x.name}</span><span>{x.grams}g</span><span>{x.have}g</span><b>{x.gap?`${x.gap}g`:"够用"}</b></div>)}</article>)}</section><section className="panel stock-panel"><Title over="FRESH INVENTORY" title="现有库存批次" action={<button className="button" onClick={()=>{const purchased=iso(),id=`custom-${Date.now()}`;set(s=>({...s,stock:[...s.stock,{id,ingredientId:id,name:"新食材",kind:"veg",grams:300,storage:"冷藏",purchased,expires:expiry(purchased,"veg","冷藏")}]}))}}>＋ 新增库存</button>}/><p className="sub">修改存放方式会自动重估到期日，也可以手动覆盖。</p><div className="stock-table"><div className="stock-row stock-head"><span>食材 / 类别</span><span>当前余量</span><span>存放</span><span>购买日</span><span>预计到期</span><span>状态</span></div>{state.stock.map(b=>{const f=fresh(b.expires);return <div className="stock-row" key={b.id}><span className="stock-name"><i className={b.kind}/><span><input value={b.name} onChange={e=>updateBatch(b.id,{name:e.target.value})}/><small>{b.kind==="meat"?"肉类":"蔬菜"}</small></span></span><label><input type="number" min="0" value={b.grams} onChange={e=>updateBatch(b.id,{grams:+e.target.value})}/> g</label><select value={b.storage} onChange={e=>{const storage=e.target.value as Batch["storage"];updateBatch(b.id,{storage,expires:expiry(b.purchased,b.kind,storage)})}}><option>冷藏</option><option>冷冻</option><option>常温</option></select><input type="date" value={b.purchased} onChange={e=>updateBatch(b.id,{purchased:e.target.value,expires:expiry(e.target.value,b.kind,b.storage)})}/><input type="date" value={b.expires} onChange={e=>updateBatch(b.id,{expires:e.target.value})}/><em className={f.cls}>{f.text}</em></div>})}</div></section></div>}
 </section><nav className="mobile-nav">{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><i>{n.icon}</i>{n.label}</button>)}</nav>
 {picker&&<Modal close={()=>setPicker(null)} title={`替换一道${picker.kind==="meat"?"荤菜":"素菜"}`}><label className="modal-search">⌕<input autoFocus placeholder="按菜名或食材搜索" value={filter.q} onChange={e=>setFilter({...filter,q:e.target.value})}/></label><div className="picker">{recipes.filter(r=>r.kind===picker.kind&&(!filter.q||`${r.name}${r.ingredients.map(x=>x.name)}`.includes(filter.q))).map(r=><button key={r.id} onClick={()=>replace(r.id)}><b style={{background:r.color}}>{r.kind==="meat"?"荤":"素"}</b><span><strong>{r.name}</strong><small>{r.ingredients.map(x=>x.name).join(" · ")} · {r.minutes} 分钟</small></span><em>{r.source==="Bryan Johnson"?"BLUEPRINT":"顾小胖灵感"}</em></button>)}</div></Modal>}
 {usageMeal&&<Modal close={()=>setUsageMeal(null)} title="确认实际用量"><p className="notice">系统优先扣减最早到期的库存批次；不足部分只记录缺口，不会出现负库存。</p><div className="usage">{aggregate(state.meals.find(m=>m.id===usageMeal)?.recipeIds||[]).map(x=><label key={x.id}><span><i className={x.kind}/>{x.name}</span><span><input type="number" min="0" value={usageDraft[x.id]??x.grams} onChange={e=>setUsageDraft({...usageDraft,[x.id]:+e.target.value})}/> g</span></label>)}</div><div className="modal-actions"><button className="button ghost" onClick={()=>setUsageMeal(null)}>取消</button><button className="button" onClick={saveUsage}>完成并扣减库存</button></div></Modal>}{toast&&<div className="toast">✓ {toast}</div>}</main>
}
function Aside({view,setView}:{view:View;setView:(v:View)=>void}){return <aside className="side"><div className="brand"><b>食</b><span><strong>拾味</strong><small>两周餐桌管家</small></span></div><nav>{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><i>{n.icon}</i>{n.label}</button>)}</nav><div className="saved"><i/>本机自动保存<small>最后更新：刚刚</small></div><p>保鲜期为经验估算，请结合包装标签与食材状态判断。</p></aside>}
function Metric({primary,icon,title,value,unit,note}:{primary?:boolean;icon?:string;title:string;value:string;unit:string;note:string}){return <article className={`metric ${primary?"primary":""}`}>{primary?<div><span>{title}</span><em>智能排期</em></div>:<b className={`badge ${icon==="肉"?"clay":icon==="购"?"gold":"leaf"}`}>{icon}</b>}<p>{primary?"":title}</p><strong>{value}<small> {unit}</small></strong><em>{note}</em>{primary&&<i><b style={{width:"100%"}}/></i>}</article>}
function Title({over,title,action}:{over:string;title:string;action?:React.ReactNode}){return <div className="panel-title"><div><span className="eyebrow">{over}</span><h2>{title}</h2></div>{action}</div>}
function Modal({close,title,children}:{close:()=>void;title:string;children:React.ReactNode}){return <div className="backdrop" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">SHIWEI TABLE</span><h2>{title}</h2></div><button className="icon" onClick={close}>×</button></header>{children}</section></div>}
